name: Pull Request

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: hansbinderup/meson-gcc:1.0
      options: --user root
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          clean: true
          set-safe-directory: true
    - name: Build release
      run: scripts/build.sh

  unit-tests:
    runs-on: ubuntu-latest
    container:
      image: hansbinderup/meson-gcc:1.0
      options: --user root
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          clean: true
          set-safe-directory: true
    - name: Build and run unit tests
      run: scripts/unit_test.sh
    - name: Test Report
      uses: phoenix-actions/test-reporting@v15
      if: success() || failure()
      with:
        name: Unit tests report
        path: .build-tests/meson-logs/testlog.junit.xml
        reporter: java-junit

