name: Pull Request

on:
  pull_request:
    branches:
      - main
      - 'feature/**'

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: hansbinderup/meson-gcc:1.1
      options: --user root
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          clean: true
    - name: Safe directory
      run: git config --global --add safe.directory '*'
    - name: Build Meltdown
      run: scripts/ci_build.sh

  unit-tests:
    runs-on: ubuntu-latest
    container:
      image: hansbinderup/meson-gcc:1.1
      options: --user root
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          clean: true
    - name: Safe directory
      run: git config --global --add safe.directory '*'
    - name: Build and run unit tests
      run: scripts/unit_test.sh
    - name: Test Report
      uses: phoenix-actions/test-reporting@v15
      if: success() || failure()
      with:
        name: Unit tests report
        path: .build-tests/meson-logs/testlog.junit.xml
        reporter: java-junit

  verify-bench:
    runs-on: ubuntu-latest
    container:
      image: hansbinderup/meson-gcc:1.1
      options: --user root
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          clean: true
          fetch-depth: 2 # action adds a merge commit on top - account for that
    - name: Safe directory
      run: git config --global --add safe.directory '*'
    - name: Verify bench
      run: scripts/verify_commit_bench.sh

  build-tuner:
    runs-on: ubuntu-latest
    container:
      image: hansbinderup/meson-gcc:1.1
      options: --user root
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          clean: true
    - name: Safe directory
      run: git config --global --add safe.directory '*'
    - name: Build tuner
      run: tuner/scripts/build.sh

  build-spsa:
    runs-on: ubuntu-latest
    container:
      image: hansbinderup/meson-gcc:1.1
      options: --user root
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
          clean: true
    - name: Safe directory
      run: git config --global --add safe.directory '*'
    - name: Build with SPSA enabled
      run: tuner/scripts/build.sh --spsa

